package betsy.grammar;

/**
 * A SentenceStructureParser takes a tree of Tags generated by an English
 * language parser like the Stanford Parser, and turns it into a tree of
 * StructureTags, which have clearer rules about how they are laid out (see
 * the StructureTag class) and provide more details on the functions of each
 * phrase in the sentence. 
 * @author jacob
 *
 */
public interface SentenceStructureParser {
	/**
	 * Generate a WordTree of StructureTags, given a tree of Tags parsed from
	 * a sentence.
	 * @param tree the Tag tree representing the input sentence.
	 * @return a tree of StructureTags, also representing the sentence
	 */
	WordTree<StructureTag> parseTree(WordTree<Tag> tree);
}
